= 2022년 oop-practice 모음
// Metadata:
:description: study
:keywords: extends
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-20220418]]
== 2022년 4월 18일 월요일

==== 학습목표 
1. extends 상속을 명확하게 알 수 있다. 
2. java에서 getter, setter 메소드 사용법을 안다. 
3. public, protected, private, default 접근제어자 사용법을 안다. 

-

하위객체는 상위객체(부모)의 특징을 물려받는다. -> 상속 +
메소드나 변수를 "구현하는가" & "사용하는가"에 따라서 상속의 형태가 달라지게 된다. +

객체 지향 프로그래밍에서 객체의 데이터는 객체 외부에서 직접적으로 접근하는 것을 막는다. +
객체 데이터를 외부에서 읽고 변경시 객체의 무결성이 깨질 수 있기 때문이다. +


외부에서 객체의 데이터를 읽을 때도 메소드를 사용하는 것이 좋은데 +
객체 외부에서 객체 필드값을 사용하기 부적절한 경우가 있다. +

=== getter, setter method
이런 경우 메소드로 필드값을 "가공 후"에 외부로 전달 -> Getter의 기능 +

데이터는 외부에서 접근하지 않도록 막고, 메소드는 공개해서 외부에서는 메소드를 통해 데이터를 접근하도록 유도한다. -> Setter의 기능 +


_필드 접근 제한자 : private_::
[source,java]
----
private 타입 fieldName;
----

_Getter 메소드 사용법_::
[source,java]
----
public 리턴타입 getFieldName() {
    return fieldName;
}
----


_Setter 메소드 사용법_::
[source,java]
----
public void setFieldName(타입 fieldName) {
    this.fieldName = fieldName
}
----


Vehicle 클래스를 getter와 setter를 사용하여 생성해보았다.
[source,java,linenums]
----
class Vehicle {
    protected int speed = 3;

    public double getSpeed() { 
        double recommendedSpeed = speed * 0.8;
        return recommendedSpeed;
    }

    public void setSpeed(int speed) { 
        if (speed < 0) {
            this.speed = 0;
            return;
        } else {
            this.speed = speed;
        }
    }
}
----

=== extends 상속
*extends는* 부모에서 선언 / 정의를 모두 하고 +
자식은 메소드나 변수를 "*그대로*" *물려받아* 사용할 수 있다. +

Vehicle 클래스를 extends를 사용하여 상속받은 Car 클래스를 생성해보았다. +

[source,java]
----
class Car extends Vehicle {
    public void printSpeed() {
        System.out.println(speed);
    }

}
----



[source,java]
----
class ExtendsSample {
    public static void main(String[] args) {
        Car Tivoli = new Car();

        System.out.println(Tivoli.getSpeed());

        Tivoli.printSpeed();
    }
}
----


=== 접근제어자

[cols=6*,options=header]
|===
|
|
|default
|private
|protected
|public

|동일 패키지 접근
|같은 클래스 접근
|o
|o
|o
|o

|//
|상속 클래스 접근
|o
|x
|o
|o

|//
|다른 클래스 접근
|o
|x
|o
|o

|다른 패키지 접근
|일반 클래스 접근
|x
|x
|x
|o

|//
|상속 클래스 접근
|x
|x
|o
|o

|===
